spring:
  application:
    name: greeting-service
management:
  endpoints:
    web:
      exposure:
          include:
            - '*'
greeting-service:
  greeting: "SETUP-SERVE,"
  default-value: "DEFAULT DO SETUP-SERVE"


